[package]
name = "zmux-term"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
zmux-transport.workspace = true

anyhow.workspace = true
bytes.workspace = true
camino.workspace = true
parking_lot.workspace = true
portable-pty.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
